import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#6b7280',
  },
  header: {
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  listContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  challanCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
    overflow: 'hidden',
  },
  challanHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
  },
  challanInfo: {
    flex: 1,
  },
  challanNo: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 3,
  },
  challanMeta: {
    fontSize: 11,
    color: '#6b7280',
    fontWeight: '500',
  },
  challanRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  grCountBadge: {
    backgroundColor: '#dbeafe',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  grCountText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2563eb',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: '600',
  },
  expandIcon: {
    fontSize: 12,
    color: '#9ca3af',
  },
  grListContainer: {
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingHorizontal: 0,
    paddingVertical: 0,
    backgroundColor: '#fafbfc',
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: '#f0f4ff',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  summaryItem: {
    alignItems: 'center',
    flex: 1,
  },
  summaryLabel: {
    fontSize: 9,
    color: '#6b7280',
    fontWeight: '500',
    marginBottom: 2,
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1f2937',
  },
  summaryDivider: {
    width: 1,
    height: 28,
    backgroundColor: '#d1d5db',
  },
  grItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  grTop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  grLeft: {
    marginRight: 10,
  },
  grBadge: {
    backgroundColor: '#2563eb',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    minWidth: 48,
    alignItems: 'center',
  },
  grBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#fff',
  },
  grMiddle: {
    flex: 1,
  },
  grRight: {
    flex: 1,
  },
  grDestination: {
    fontSize: 12,
    fontWeight: '600',
    color: '#374151',
  },
  grDetail: {
    fontSize: 10,
    color: '#6b7280',
    marginTop: 1,
  },
  grActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginLeft: 8,
  },
  signalBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
  },
  redSignal: {
    backgroundColor: '#fef2f2',
    borderColor: '#f87171',
  },
  redSignalActive: {
    backgroundColor: '#dc2626',
    borderColor: '#b91c1c',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 6,
  },
  greenSignal: {
    backgroundColor: '#f0fdf4',
    borderColor: '#22c55e',
  },
  greenSignalActive: {
    backgroundColor: '#16a34a',
    borderColor: '#15803d',
    shadowColor: '#22c55e',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 6,
  },
  signalIcon: {
    fontSize: 14,
    opacity: 0.5,
  },
  signalIconActive: {
    opacity: 1,
  },
  grStatusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
    marginLeft: 58,
  },
  statusTag: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: '#f0fdf4',
  },
  statusTagRedBg: {
    backgroundColor: '#fef2f2',
  },
  statusTagRed: {
    fontSize: 9,
    fontWeight: '600',
    color: '#dc2626',
  },
  statusTagGreen: {
    fontSize: 9,
    fontWeight: '600',
    color: '#166534',
  },
  noGrText: {
    fontSize: 12,
    color: '#9ca3af',
    fontStyle: 'italic',
    paddingVertical: 4,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: 12,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 4,
  },
  emptySubtext: {
    fontSize: 14,
    color: '#9ca3af',
  },
  loadMoreContent: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 16,
    gap: 8,
  },
  loadMoreText: {
    fontSize: 13,
    color: '#6b7280',
  },
  loadMoreBtn: {
    backgroundColor: '#2563eb',
    marginHorizontal: 40,
    marginVertical: 16,
    paddingVertical: 13,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#2563eb',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  loadMoreBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 0.3,
  },
  endOfList: {
    alignItems: 'center',
    paddingVertical: 16,
  },
  endOfListText: {
    fontSize: 12,
    color: '#9ca3af',
  },

  // Kaat info on GR items
  kaatInfoRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 3,
  },
  kaatTag: {
    fontSize: 9,
    fontWeight: '600',
    color: '#7c3aed',
    backgroundColor: '#f5f3ff',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },

  // Add button in expanded challan
  addKaatBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f3ff',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  addKaatBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#7c3aed',
  },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 30,
    maxHeight: '85%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1f2937',
  },
  modalClose: {
    fontSize: 20,
    color: '#9ca3af',
    padding: 4,
  },
  modalSubtitle: {
    fontSize: 12,
    color: '#6b7280',
    marginBottom: 14,
  },
  modalToggleRow: {
    flexDirection: 'row',
    backgroundColor: '#f3f4f6',
    borderRadius: 10,
    padding: 3,
    marginBottom: 14,
  },
  modalToggleBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
  },
  modalToggleActive: {
    backgroundColor: '#7c3aed',
    shadowColor: '#7c3aed',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  modalToggleText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6b7280',
  },
  modalToggleTextActive: {
    color: '#fff',
  },
  modalInput: {
    backgroundColor: '#f9fafb',
    borderWidth: 1.5,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 10,
  },
  selectAllBtn: {
    paddingVertical: 6,
    marginBottom: 4,
  },
  selectAllText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#7c3aed',
  },
  modalGrList: {
    maxHeight: 280,
    marginBottom: 14,
  },
  modalGrItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  modalCheckbox: {
    fontSize: 20,
    color: '#7c3aed',
    marginRight: 12,
    fontWeight: '600',
  },
  modalGrInfo: {
    flex: 1,
  },
  modalGrNo: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1f2937',
  },
  modalGrMeta: {
    fontSize: 11,
    color: '#6b7280',
    marginTop: 1,
  },
  modalGrExisting: {
    fontSize: 10,
    color: '#7c3aed',
    marginTop: 2,
    fontWeight: '500',
  },
  modalSaveBtn: {
    backgroundColor: '#7c3aed',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#7c3aed',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  modalSaveBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
});
